Issue 67, Part 2: Release script & dockerhub integration
softwaremill/fabrica pull request #92
Opened 2020-11-26 08:48 UTC by Hejwo

2020-11-30 07:38 UTC, dzikowski requested changes

2020-11-30 07:38 UTC, dzikowski commented on fabrica.sh
>      -v $(pwd):/network/target \
do `network/target` powinno trafiać `FABRICA_NETWORK_ROOT`

2020-11-30 07:38 UTC, dzikowski commented on fabrica.sh
> +    -v $(pwd):/network/target \
do `network/target` powinno trafiać `FABRICA_NETWORK_ROOT`

2020-11-30 07:38 UTC, dzikowski commented on fabrica.sh
> +  sudo curl -Lf https://github.com/softwaremill/fabrica/releases/download/"$version"/fabrica.sh -o /usr/local/bin/fabrica.sh && sudo chmod +x /usr/local/bin/fabrica.sh
`/usr/local/bin/fabrica.sh` jest ryzykowne, przecież różni ludzie mogą to trzymać w różych miejscach (w `opt`, albo w samym `bin`). imho powinien tutaj być podmieniany bieżący plik

2020-11-30 07:38 UTC, dzikowski commented on generators/version/index.js
> +      supported: {
👍

2020-11-30 07:38 UTC, dzikowski commented on fabrica-release.sh
> +FABRICA_VERSION=$(cat "$FABRICA_HOME"/package.json | jq -r '.version')
`jq` nie przyjmuje pliku jako input, albo parametr?

2020-11-30 07:38 UTC, dzikowski commented on fabrica-release.sh
> +echo "   FABRICA_VERSION: $FABRICA_VERSION"
pewnie się czepiam, ale **trzy** spacje? 😉

2020-11-30 07:38 UTC, dzikowski commented on fabrica.sh
> +    Updates Fabrica to specified version."
README nie jest zaktualizowane

2020-11-30 07:38 UTC, dzikowski commented on fabrica.sh
>      Prints current fabrica version, with optional details.
`fabrica` w helpach i dokumentacji piszemy z małej czy dużej?

2020-11-30 07:38 UTC, dzikowski commented on fabrica.sh
> +    docker run -it --rm \
a w ogóle nie podoba mi się to wielokrotne wywoływanie dockera wszędzie, tutaj chodzi po prostu o przekazanie commanda dalej do yeomana, samo wywołanie dockera można opakować w jakąś funkcję

2020-11-30 07:38 UTC, dzikowski commented on generators/check-updates/index.js
> +    const allNewerVersions = this._getAllNewerVersions(version, allAvailableVersions);
`allAvailableVersions` jest użyte tylko wewnątrz `_getAllNewerVersions` - może je tam schować?

2020-11-30 07:38 UTC, dzikowski commented on generators/check-updates/index.js
> +  async checkUpdates() {
a nie `checkForUpdates`?

2020-11-30 07:38 UTC, dzikowski commented on generators/check-updates/index.js
> +      .sort((a, b) => new Date(b.last_pushed) - new Date(a.last_pushed))
nie do końca, nowszą wersję determinuje się po numerku, a nie po dacie (możesz np. puścić bugfixy starszej wersji)

2020-11-30 07:38 UTC, dzikowski commented on generators/check-updates/index.js
> +  }
całość można przepisać na coś w stylu 

```javascript
return tagsResponse.results
  .map(({ name }) => name)
  .filter((name) => name  !== 'latest' && name > currentVersion)
  .sort();
```

2020-11-30 07:38 UTC, dzikowski commented on generators/validate/index.js
> +      this.log(chalk.bold(`- ${event.message}`));
dlaczego tu jest `-` na początku?

2020-11-30 07:38 UTC, dzikowski commented on generators/check-updates/index.js
> +    if (typeof this.options.compatible === 'undefined') {
`if (!this.options.compatible)` powinno wystarczyć

2020-11-30 08:24 UTC, Hejwo commented on fabrica.sh
> +  echo "    FABRICA_IMAGE:       $FABRICA_IMAGE"
?

2020-11-30 08:24 UTC, Hejwo commented on fabrica.sh
> +    docker run -it --rm \
?

2020-11-30 08:26 UTC, Hejwo commented on fabrica.sh
> +elif [ "$COMMAND" = "updateTo" ]; then
a może `use` ? tak samo jest w sdk manie

2020-11-30 08:28 UTC, Hejwo commented on fabrica.sh
> +elif [ "$COMMAND" = "updates" ]; then
hm... i tak i nie. myślałem o tym, ale kiedy robimy `update --list` to czy nie oczekujemy że będzie też samo `update` ?

2020-11-30 08:28 UTC, Hejwo commented on fabrica.sh
> +    $FABRICA_IMAGE sh -c "/fabrica/docker-entrypoint.sh validate fabrica-config.json"
nie

2020-11-30 08:28 UTC, Hejwo commented on fabrica.sh
> +    -v $(pwd):/network/target \
?

2020-11-30 08:28 UTC, Hejwo commented on fabrica.sh
> +    $FABRICA_IMAGE sh -c "/fabrica/docker-entrypoint.sh check-updates"
nie

2020-11-30 08:29 UTC, Hejwo commented on fabrica.sh
>      -v $(pwd):/network/target \
ok, tutaj mamy generalne zamieszanie. chciałbym o nim pogadać trochę dłużej.

2020-11-30 08:30 UTC, Hejwo commented on fabrica.sh
> +    -v $(pwd):/network/target \
ok, tutaj mamy generalne zamieszanie. chciałbym o nim pogadać trochę dłużej.  
duplikaty zamykam.

2020-11-30 08:31 UTC, Hejwo commented on fabrica-release.sh
> +FABRICA_VERSION=$(cat "$FABRICA_HOME"/package.json | jq -r '.version')
nie ma. szukałem.

2020-11-30 08:31 UTC, Hejwo commented on fabrica-release.sh
> +echo "   FABRICA_VERSION: $FABRICA_VERSION"
:*

2020-11-30 08:33 UTC, Hejwo commented on fabrica.sh
>      Prints current fabrica version, with optional details.
z dużej ;). poprawione

2020-11-30 08:59 UTC, Hejwo commented on generators/validate/index.js
> +      this.log(chalk.bold(`- ${event.message}`));
żeby był ładna kreska do komnikatu z błędem

2020-11-30 09:00 UTC, Hejwo commented on generators/check-updates/index.js
> +      .sort((a, b) => new Date(b.last_pushed) - new Date(a.last_pushed))
?

2020-12-02 10:31 UTC, Hejwo commented on fabrica.sh
> +    -v $(pwd):/network/target \
wyniesione do https://github.com/softwaremill/fabrica/issues/97

2020-12-03 14:00 UTC, Hejwo commented on generators/check-updates/index.js
> +      .sort((a, b) => new Date(b.last_pushed) - new Date(a.last_pushed))
nieaktualne

2020-12-03 14:01 UTC, Hejwo commented on generators/check-updates/index.js
> +  }
nieaktualne - inaczej to już robimy

2020-12-04 07:17 UTC, dzikowski commented on generators/list-versions/index.js
> +      .sortVersions(allVersions)
a dlaczego getAvailableTags nie zwraca posortowanych?

2020-12-04 07:17 UTC, dzikowski commented on generators/list-versions/index.js
> +    this.log(JSON.stringify(versionsSortedAndMarked, null, 2));
tego nie czaję - niby wypluwamy JSON, który jest ustruktyzowany, może być dalej przetwarzany itd. ale w tym JSONie nie mamy wartości do użycia przez inne skrypty, tylko stringi sztucznie obrobione tak, żeby łatwo je było przeczytać użytkownikowi.

imho tutaj powinniśmy wypluć przyjazny dla użytkownika output, najprościej pewnie listę wersji w osobnych linijkach, ew. oznaczone jako current i compatible (co to w ogóle znaczy compatible?)

2020-12-04 07:17 UTC, dzikowski commented on package.json
> +    "mocha": "^8.2.1",
po co nam to?

2020-12-04 07:17 UTC, dzikowski commented on samples/fabricaConfig-1org-1channel-1chaincode-tls.json
> +  "fabricaVersion": "0.0.10",
`10`?

2020-12-04 07:17 UTC, dzikowski commented on package.json
> +  "version": "0.0.0",
dlaczego `0.0.0`?

2020-12-04 07:17 UTC, dzikowski commented on e2e/versionSort.test.js
> +    assert.deepEqual(sortedVersions, expectedVersions);
`expect(sortedVersions).toEqual(expectedVersions);`

2020-12-04 07:17 UTC, dzikowski commented on package.json
> +    "mocha": "^8.2.1",
teraz widzę - Jest.js ma sam matchery na to, Mocha do wywalenia

2020-12-04 07:17 UTC, dzikowski commented on generators/list-compatible-updates/index.js
> +      this.log(`${chalk.underline.bold('Compatible')} versions: ${JSON.stringify(versionsToPrint, null, 2)}`);
JSON w stringu, ja bym dał `${versionsToPrint.join(', ')}`

2020-12-04 07:17 UTC, dzikowski commented on generators/repositoryUtils.js
> +    .reverse();
👍

2020-12-04 08:49 UTC, Hejwo commented on samples/fabricaConfig-1org-1channel-1chaincode-tls.json
> +  "fabricaVersion": "0.0.10",
good catch :clap: zmieniłem

2020-12-04 09:01 UTC, Hejwo commented on fabrica.sh
> +    $FABRICA_IMAGE sh -c "/fabrica/docker-entrypoint.sh validate ../fabrica-config.json"
nie działało

2020-12-04 09:06 UTC, Hejwo commented on generators/list-compatible-updates/index.js
> +      .filter((name) => name.startsWith('0.0.') && name > version);
jest używane. Kiedy robimy validate lub generate to jeśli są nowsze kompatybilne wersje to wyskakuje info.

2020-12-04 09:07 UTC, Hejwo commented on generators/list-compatible-updates/index.js
> +      .filter((name) => name.startsWith('0.0.') && name > version);
a startsWith zmieniłem na `config.isFabricaVersionSupported(` bo tak powinno być.

2020-12-04 09:14 UTC, Hejwo commented on fabrica.sh
> +    $FABRICA_IMAGE sh -c "/fabrica/docker-entrypoint.sh $passed_command"
celowo. inaczej docker się krzaczy

2020-12-04 09:55 UTC, dzikowski approved these changes

2020-12-07 07:00 UTC, dzikowski commented on generators/config.js
> +}
a dlaczego nie po prostu?:

```javascript
const supportedVersionPrefix = version.split('.').slice(0, 2).join('.') + '.';
```

2020-12-07 08:04 UTC, merged